# Generated by Django 3.2.9 on 2021-11-30 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freq_bill', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('last_login', models.DateTimeField()),
                ('online_status', models.BinaryField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('saver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
                ('saving_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.saving')),
            ],
        ),
        migrations.AddField(
            model_name='saving',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
