# Generated by Django 3.2.9 on 2021-11-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='online_status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
