# Generated by Django 3.2.9 on 2021-12-01 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_online_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='saver_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='saving_name',
        ),
        migrations.DeleteModel(
            name='Saving',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
