# Generated by Django 3.2.9 on 2021-12-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='saving',
            name='status',
            field=models.CharField(default='belum lunas.', max_length=12),
        ),
    ]
