# Generated by Django 3.2.9 on 2021-12-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0002_saving_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='create_date',
            field=models.DateField(),
        ),
    ]
