# Generated by Django 3.2.9 on 2021-12-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0003_alter_saving_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saving',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
