# Generated by Django 3.2.9 on 2021-12-05 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0004_rename_create_date_saving_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='freq_bill',
        ),
        migrations.AddField(
            model_name='saving',
            name='jumlah_pembayaran',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='saving',
            name='notice_every',
            field=models.CharField(default='bulan', max_length=6),
        ),
    ]
