# Generated by Django 3.2.9 on 2021-12-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0005_auto_20211205_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='notice_every',
        ),
    ]
